# Generated by Django 3.2.19 on 2023-05-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20230523_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
