# Generated by Django 3.2.19 on 2023-05-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_booking_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
