# Generated by Django 3.2.19 on 2023-05-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20230524_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
